amiv-eth/amivapi

- amivapi/models.py
- amivapi/schemas.py
Not sure why it needed to be there anyways.
It seems to not break anything, but maybe we have some untested functionality here?
Hermann, you added this: Is this field necessary for something I cant see?
> Removed "foreign key" property of "email" field in eventsignups

- amivapi/joboffers/__init__.py
- amivapi/tests/fixtures.py
- amivapi/tests/joboffers/test_joboffers.py
We discussed the requirements of job offers.
It was decided, that any joboffer will always have a pdf and a company logo, therefore we can make them required. This makes integration with CRM and displaying more reliable as well.
In addition we want a flag, that controls whether the job offer is shown on the website. This is important, as some companies want to take a job offer offline, when the job is given to someone. In addition we would like a possibility in the future, where companies can create joboffers themselves on the kontakt page. That means we want to review them before publishing, which we can, if the flag can prevent it from being shown.
> Added show_website flag to joboffers and reworked other fields

- amivapi/events/validation.py
later_than and earlier_than threw exceptions if the referenced value
was missing. This was not prevented by required flags, as the validators
were executed anyway. Also this masked all other messages with the exception
making it hard to detect the problem for users.
> Fixed exception in later_than and earlier_than validators

- amivapi/media.py
- amivapi/tests/test_media.py
Eve expects the file updated time to have UTC tzdata. See issue #150
> Fix for #150

- amivapi/tests/auth/test_session_expiry.py
Periodic functions were scheduled to a time, which was never reached
due to the frozen time. The @periodic decorator was called before the
time was frozen.
> Fixed bug in test_session_expiry

- amivapi/events/__init__.py
- amivapi/events/authorization.py
- amivapi/events/emails.py
- amivapi/events/model.py
- amivapi/events/queue.py
- amivapi/events/validation.py
- amivapi/settings.py
- amivapi/tests/events/test_auth.py
- amivapi/tests/events/test_emails.py
- amivapi/tests/events/test_model.py
- amivapi/tests/events/test_projections.py
- amivapi/tests/events/test_queue.py
- amivapi/tests/events/test_validators.py
- amivapi/tests/fixtures.py
- amivapi/utils.py
Restructured the tests, generally tidied up code of event module.
There is now a field `selection_strategy` in events and `accepted` in eventsignups. These are used for different methods to give spots to people. FCFS and manual setting are supported. Also emails are sent, when people are automatically admitted to an event. The emails contain a link to give up the spot and let other people get promoted.
> Improvements of signups

- amivapi/events/model.py
- amivapi/events/validation.py
- amivapi/tests/events/test_auth.py
- amivapi/tests/events/test_model.py
- amivapi/tests/events/test_validators.py
This PR fixes #158 and #91, aswell as a minor bug in some event-validator.
*Debatable*: json-schema are more complex than cerberus-schema. I now require the user to specify a full json-schema for additional_fields, while ensuring in the validator that the following fields are always set accordingly:
{
"$schema": "http://json-schema.org/draft-04/schema#",
"type": "object",
"additionalProperties": False
}
This is necessary to ensure that additional_fields specifies a dict and not a list (which makes it easier for an UI to create an understandable, dynamic form for these fields), aswell as to ensure the correct usage of json-schema to our purposes. One could also overwrite this api-side, but it would be instransparent to let somebody submit a non-complete json-schema and add or overwrite …
> use jsonschema in additonal_fields of events

- amivapi/auth/apikeys.py
- amivapi/cli.py
- amivapi/groups/validation.py
- amivapi/settings.py
- amivapi/tests/auth/test_apikeys.py
- amivapi/tests/test_media.py
- amivapi/utils.py
I was starting to write tests for the CLI when I thought: Do API Keys really need to be handled with CLI?
I think they would work better as an API resource.
Benefits:
- They could be managed more easily with admintools
- With database backups API keys will also be safed
- We don't need an additional config file for the keys.
Since the functionality provided is the same I can't see any downsides.
Instead of creating an issue I thought I'd go ahead an just implement it. What are your opinions?
> Apikeys as resource

- amivapi/documentation.py
If the documentation was requested as /docs/ instead of /docs a
wrong URL /docs//api-docs was generated for the spec, which resulted
in an error 404.
> Fixed: Documentation does not load after refresh

- amivapi/events/model.py
Corrected the default value for the field `checked_in` in the `eventsignups `schema. This is so to differentiate between someone who checked in, some who did not check in, and the case where nobody cared to check.
> Correct checked_in default value

- amivapi/auth/auth.py
- amivapi/tests/auth/test_auth.py
Prevent the API from crashing when an empty token is provided for authentication.
> Fix issue #219

- amivapi/cli.py
- amivapi/groups/mailing_lists.py
- amivapi/settings.py
- amivapi/tests/groups/test_mailing_lists.py
- amivapi/tests/utils.py
If no forward directory is specified, the api now won't store any forward files.
Furthermore, a CLI command is added to re-create all forward files if needed.
> Improve mailing list config handling.

- amivapi/groups/model.py
- amivapi/tests/groups/test_model.py
As of now, the amiv cloud is still in development. We should rename this field as long as it is not used in production.
I urge to rename this field to avoid confusion in the future.
> Rename `has_zoidberg_share` to `requires_storage` (Resolves #182)

- README.md
- amivapi/cli.py
- amivapi/groups/mailing_lists.py
- amivapi/settings.py
- amivapi/tests/groups/test_mailing_lists.py
Until now, mailing list files are created locally.
For the mailing lists to actually work, they need to be copied to a remote
server.
This copying is now included in AMIVAPI, which has two main benefits:
- No local files are required anymore, useful for future deployment with docker
- No external copying tool is required to make mailing lists work with amivapi
Unfortunately, the mailing list server supports *only* ssh connections,
therefore we have no other option to transfer the files.
While I do not think this is a very *good* solution, I believe its the *best*
approach we have available.
Closes #239.
> Create mailing list files remotely via ssh.

- Dockerfile
- README.md
- amivapi/settings.py
The pymongo driver does not like preforking, which is used by uwsgi.
The uwsgi command is now adjusted to avoid preforking.
Additionally, the README now explains how to use the docker container.
(Also the default settings are updated to make deployment easier)
> Dockerfile: uwsgi w/o preforking, Readme: Docker instructions

- .dockerignore
- Dockerfile
- README.md
- server.py
In the production setup, `uwsgi` was causing troubles by dropping connections
if to many requests occured.
I suspected bad configuration but was not able to fix it.
Searching for a solution, I came across [bjoern](https://github.com/jonashaag/bjoern),
a lightweight wsgi-server based on libev.
bjoern solves our problems:
- no dropped connections anymore
- bonus: smaller image
- bonus: runs with less memory
- bonus: no configuration required
Additionally, a `.dockerignore` is added to clean up the image a little. Essentially it just copies the `.gitignore`
> Switch from uwsgi to bjoern

- amivapi/ldap.py
- amivapi/tests/utils.py
I was just importing missing users from LDAP and had to discover that the
ISG apparently is not that much into data validation, at least not when it
comes to LDAP.
A few (2, to be precise) users are missing the `departmentNumber` field
we need to determine the department.
In this case, the API should not crash but rather assume that the user
has no department.
> Bugfix: Missing `departmentNumber` in ldap should not crash the API

- amivapi/settings.py
I cannot into regex.
It was set up to allow whitelisting `localhost` for development, but I only tested it
for `localhost:5000` (since thats what I needed locally) and the settings did not allow just `localhost`.
Fixed now.
> Fix: Regex for localhost oauth

- amivapi/groups/model.py
As so many other relationships, it makes things easier if the group-moderator is embeddable.
> Make group-moderator embeddable

- amivapi/tests/users/test_security.py
- amivapi/users/__init__.py
- amivapi/users/security.py
Fields like legi number are hidden from non-admin users.
Nevertheless, it was possible to query for those fields, e.g. for a
particular legi number, which will only return a single result.
And even if the legi number is hidden, since it is unique it can be
matched to its user without problem.
Changes:
- Eve already allows restricting query parmeters, which is now done
dynamically for user requests
- Test included
> Stop non-admins from querying restricted fields.

- amivapi/auth/sessions.py
- amivapi/tests/auth/test_sessions.py
For most OAuth usecases, accessing tools will have the token and might need to verify whether the session still exists.
This change is intended to make the process even simpler, by allowing requests of the form `GET /sessions/<token>`.
> Allow session lookup via token.

- requirements.txt
to make sure that changes to the eve-swagger we use do not crash production systems, changes in eve-swagger should always require an update of the requirements and therefore at least a CI test.
> specify version of eve-swagger

- amivapi/events/model.py
There are 3 different states which all describe that an event has no price:
* the price field in the event is not set
* the price field in the event is set to `null`
* the price field in the event is set to `0`
In order to reduce confusion, I propose to set the minimum value of the event price to `1`, thus removing the third option above. The first to options are pretty standard for all fields in our api, so they seem a reasonable choice.
> increase minimum price for event to 1

- amivapi/tests/auth/test_oauth.py
- amivapi/tests/auth/test_session_expiry.py
- amivapi/tests/users/test_security.py
- amivapi/users/model.py
Implements the minimal password policy discussed in issue #234 .
Resolves #234.
> Set minlength for password

- amivapi/events/authorization.py
- amivapi/tests/events/test_auth.py
Allows write access to `/eventsignups` for non-admins only within the registration window.
Admins can write to the resource at all time.
Write access means `POST`, `PATCH` and `DELETE`.
Resolves #240.
> Add write restrictions for eventsignups

- amivapi/events/model.py
- amivapi/tests/events/test_model.py
- amivapi/tests/test_sentry.py
- amivapi/tests/utils.py
- amivapi/validation.py
First of all, the test config would load sentry config from a file in the
current working dir. Not anymore :)
Furthermore, eventsignups with email would crash the API.
To fix this, a proper combination of `required` and `exclude` was needed,
which is able to to ignore None values. (None equals not set)
As Cerberus is a bit inconsequential about None values
(e.g. they can be ignored for `required`, but not for `exclude`), this
required patching how Cerberus handles exludes.
Resolves #213
> Fix test config and eventsignup validation

- amivapi/cli.py
`ModuleNotFoundError` was only introduced in python 3.6.
> Replace ModuleNotFoundError with ImportError for compatibility

- amivapi/groups/model.py
- amivapi/utils.py
- amivapi/validation.py
We use additional schema rules such as 'description' to make our
schema more descriptive. However, Cerberus will complain about
unknown schema rules, so they have to be defined somewhere,
even if they don't do anything.
Currently, this is done in the documentation sub-module.
This is  a bit problematic, as our API is designed with replaceable
modules in mind -- but deactivating or replacing the doc module would
now cause errors in *all* schemas.
As the additional description rules are important whether or not we
use the online docs, I have moved the rules into the general validator.
> Move schema description validation rules into general validator

- amivapi/auth/link_methods.py
- amivapi/tests/auth/test_link_methods.py
- amivapi/tests/fixtures.py
Previously, link methods would check the `title` field to identify a link
resource, which does not work if an alternative title is used.
This issue can be resolved by using the `href` field, as the key in the `DOMAIN` dict equals the endpoint URL.
> Make link methods compatible with custom resource titles

- amivapi/bootstrap.py
- amivapi/cli.py
- amivapi/settings.py
- amivapi/tests/test_media.py
- amivapi/tests/utils.py
Eve does not allow schemas to contain fields such as `_id` or `_etag`.
However, we want to create them for better documentation.
This is no problem if we add them after Eve's check (which cannot be disabled :/),
but in the current implementation, this would all mutate the domain dict defined in settings.
Thus, if a second app were to be created in the same python interpreter, the domain would already be filled and Eve would complain.
Until now, this was only an issue with the tests, so I reset the domain after each test run.
However, due to a small mistake, the CLI would call `create_app` twice.
Normally, this should not be an issue. However, the situation explained above would cause Eve to complain and crash.
Now I decided to fix the problem more properly:
Instead of a fixed dict in …
> Fix domain initialization

- amivapi/events/model.py
- amivapi/events/validation.py
- amivapi/tests/events/test_model.py
Currently the email of a user can be used for an anonymous signup, which does not make sense.
Users should only signup as users, not anonymously with their email addresses.
Resolves #330
> Inhibit public signups with user mail addresses

- amivapi/settings.py
I forgot to increment the version when implementing #333.
As it is quite important for useful sentry reports etc. to have an accurate version number,
I want to do this now :)
> Increment version for new eventsignups validation

- amivapi/events/model.py
- amivapi/settings.py
The aspect ratio for the event thumbnail image is wrong in the documentation. The thumbnail must have an aspect ratio of 1:1.
> Fix typo in events documentation

- amivapi/studydocs/__init__.py
- amivapi/studydocs/model.py
- amivapi/studydocs/summary.py
- amivapi/tests/studydocs/test_summary.py
Currently, we have a lot of metadata for study docs, but no efficient way to search through it.
In order to provide users a menu to select professors, for example, an application would have to download *all* study documents to learn the possible professors.
On the other hand, this information is much needed, as most students will not know from the top of their head how exactly their professors name might be written or if their lecture can be found as 'Analysis' or 'Analysis I'
This defeats the purpose of filtering study documents with metadata.
Thus, this commit adds the possibility to request a server-side summary of metadata by appending `summary` to the query string, e.g.
```/studydocuments?summary```
The response then contains a new meta field `_summary`, which lists the available …
> Metadata summary for study documents

- amivapi/events/validation.py
- amivapi/settings.py
- amivapi/tests/test_media.py
- amivapi/tests/utils.py
- amivapi/validation.py
I have noticed that Cerberus swallows exceptions.
I modified the test framework to detect this.
This showed two errors in our validators. One was a missing
return statement, the other was more fundamental:
Whenever a file validator would register an error, Cerberus
would crash, as it internally saved the validated value
and for some reason deepcopies it during the processing.
File buffers couldn't be deepcopied, causing a crash.
I have solved this by removed the reference to the validated
value, as it is *never* used anyways.
(I have no clue why it is in there in the first place)
> Media validation exception

- amivapi/events/model.py
- amivapi/settings.py
We specified the aspect ratio as height:width, but validate it width:height, which I now corrected.
While at it, I improved the respective docs a little.
> Use correct ratio (portrait) for event posters, update docs.

- amivapi/events/model.py
- amivapi/settings.py
The description text with 'cents' is more confusing than helpful to users.
> change cents to rappen

- amivapi/events/emails.py
- amivapi/events/queue.py
The email tests failed because the token could not be decoded. This PR fixes this.
The tokens were returned as bytes, and for some reason, the `url_for` that turns the token into
a clickable link would take the `b'...'` and apply some escaping, resulting in `b%27...%27`.
This is not intended, the tokens should be included as utf-8 strings in the link.
I'm not quite sure why the tests did not fail before, but now everything is working as intended.
> Fix token in email

- amivapi/auth/auth.py
- amivapi/auth/link_methods.py
- amivapi/events/model.py
- amivapi/joboffers/__init__.py
- amivapi/tests/auth/test_auth.py
- amivapi/tests/auth/test_link_methods.py
- amivapi/users/security.py
For the home endpoint, some link methods were incorrect, i.e. the API would report that some methods are allowed for the current user (although they were not) and some of the reported methods would not be allowed.
This was the result of to unrelated problems:
1. Not allowed `HEAD`: Eve automatically allows `HEAD` requests if `GET` is possible. However, if `GET` is set to `public_methods`, `HEAD` *is not* automatically included, and has to be set explicitly. Unaware of this, the API would report that `HEAD` is allowed, while it was not. I have corrected the respective resource configs such that `HEAD` is allowed whenever `GET` is, as it is intended.
2. Allowed `GET` if it is not: Some resources using `AdminOnlyAuth` would not create a user lookup filter, but instead `abort`. The API had no …
> Fix home link methods

- amivapi/validation.py
By popular request, all acpect ratios are now validated with some tolerance.
Closes #367.
> Validate all aspect ratios with tolerance

- amivapi/events/model.py
- amivapi/events/projections.py
- amivapi/tests/events/test_projections.py
The `signup_count` was introduced such that people who do not see the signups know whether an event is full or not. However, so far also unaccepted signups are counted in, contradicting it's purpose.
With this PR we split between unaccepted and accepted signups. Fixes #364
> Signup count split between accepted and unaccepted

- amivapi/utils.py
check if argument is a string or a list of strings. If it is a string convert to [string]
> Fix issue 348 (semicolons between characters of To email address)

- README.md
- amivapi/events/emails.py
- amivapi/settings.py
- amivapi/utils.py
All API mails are sent from the same address, thus the `mail` util
does not require a sender mail anymore, and instead always uses
the API mail from the config.
Additionally, the mail function now adds an configurable prefix
to the mail subject, e.g. "[AMIV]", to increase consistency and
allow users to spot API mails quickly.
> Improve mail function

- amivapi/settings.py
During the coding weekend, I forgot to enforce incrementing the version
number in each pull request. However, for useful error reports in Sentry,
the version number is important.
This commit set the API to a 'post-codingweekend' version.
> Increment version number.

- amivapi/settings.py
- amivapi/utils.py
- requirements.txt
For editing file lists comfortably, in particular to replace single files, clients need to download all files, as Eve currently accepts only the list as a whole for patches, i.e. single items cannot be replaced without sending all others.
Downloading the files in javascript is currently impossible, as Eve does not supply the needed CORS headers to the media endpoint. Eve 0.8.2 fixes this, but is not yet released.
As file list editing of significant importance for the new amiv website (for studydocs), we have decided to switch to the currentl development branch of Eve. We can switch back to pypi as soon as 0.8.2. is released.
Aside from that, Eve made some internal changes to the response class, which required an update to one of our hooks for the case of file passthrough.
> Push Eve to 0.8.2 (dev branch for now).

- amivapi/joboffers/__init__.py
The name of the English title field was the same as for the German one. As this terms are used to generate the form for the Admintool, it should state the correct language.
> Fix typo in resource definition for joboffers

- .dockerignore
- Dockerfile.test
- amivapi/auth/apikeys.py
- amivapi/events/validation.py
- amivapi/groups/model.py
- amivapi/settings.py
- amivapi/tests/auth/test_auth.py
- amivapi/tests/auth/test_sessions.py
- amivapi/tests/fixtures.py
- amivapi/tests/utils.py
- amivapi/users/security.py
- amivapi/validation.py
- requirements.txt
For some reason, the generic alpine image would not correctly update
the repositories and would not find mongodb.
With a fixed version, this issue does not occur anymore.
Additionally, important changes due to version update:
- Pytz: Dependency removed, as datetime
can handle utc on its own.
- Cerberus: `valueschema` renamed to `valuesrules`.
- MongoDB: `insert` is replaced by `insert_one` and `insert_many`.
As a consequence, ObjectIDs are retrieved
a bit differently.
- PassLib: `encrypt` renamed to `hash`.
`vary_round` is deprecated, has it
"provided little security and was not worth
the additional complexity" [1].
[1]: https://passlib.readthedocs.io/en/stable/history/1.7.html?highlight=vary_rounds#crypt-context-api-deprecations
Closes #394 (new eve version fixes this bug)
> Update requirements and test setup.

- amivapi/settings.py
There is a subtle difference between `no-store` and `no-cache`.
`no-store`: Never return from cache, always request new. (Especially problematic for images, which are always re-loaded.) **This is what we currently have**.
`no-cache`: Don't return from cache by default, but first re-validate with the server, in our case using the `If-Modified-Since` header, which browsers use automatically, as eve includes `Last-Modified` headers in all responses. **This is what we actually want.**
Thus, with this small change, the api should cache in the way we want. Stale results from cache will never be returned without a request, and data is only transmitted if anything has changed.
More info: https://www.keycdn.com/blog/http-cache-headers
Note: Having both `no-cache` and `must-revalidate` doesn't …
> Allow proper caching with `If-Modified-Since`.

- amivapi/ldap.py
- amivapi/settings.py
- amivapi/tests/test_ldap.py
As of fall 2019, the LDAP data for students has changed.
The general string from which we detect membership has moved from the `departmentNumber` field to the (new) `description` field.
Unfortunately, the info for all previous students is still in the
`departmentNumber` field, thus we now check which of both fields is in use before
parsing.
> Fix ldap membership detection (students >2019).

- amivapi/ldap.py
In #398, we introduced parsing a (new) LDAP field `description`, which substitutes the old
`departmentNumber` field for new students.
We have however noticed that the `departmentNumber` field still exists for (only a few) of the
new students, however with uninformative input such as "Student".
To ensure smooth operation, we should thus check the description field first, as it is the
new official field with the information we need, and only fall back to the departmentnumber field
if it is missing.
> LDAP: prefer description over departmentNumber.

- amivapi/ldap.py
- amivapi/tests/test_ldap.py
Ensures that the newsletter is subscribed when new members are imported/updated from LDAP.
Fixes #400
> Fix newsletter subscription with LDAP user import (Fix #400)

- amivapi/events/queue.py
- amivapi/tests/events/test_queue.py
Fixes the accepted signup POST issue when the action is performed by an admin.
> Fix FCFS POST issue for admins (fix #381)

- amivapi/events/emails.py
- amivapi/tests/events/test_emails.py
Ensures that a confirm email is sent to an event signup by email even
when "user" is set to null in the request payload.
**Previous behavior**
No confirm email was sent to the given email address, when `user` is in the request payload although its value is set to the default value `null`.
```
{
"event": "<event-id>",
"user": null,
"email": "test@bla.ts"
}
```
With this PR, a confirmation email is also sent in this case.
> Fix issue for sending event signup confirm email

- amivapi/studydocs/model.py
This PR adds two new types of study documents: `oral exams` and `study guides`.
- `oral exams` are introduces mainly for maintenance. We received complaints that it is hard to get an overview of available oral exams because it is currently impossible to differentiate them from normal exams.
- `study guides` are mainly intended for the AMIV PVK, but also for similar amiv-hosted courses that provide guides in form of scripts or presentations to students. They are different from `cheat sheets`, as they are much more extensive. And they are different from `lecture documents`, as they are neither official documents, nor necessarily follow the lecture structure (e.g. a PVK might cover the topics of a lecture, but present them in different order and context). Finally, there is a need for …
> Add `oral exams` and `study guides` to study document types.

- amivapi/auth/sessions.py
- requirements.txt
The LDAP sync requires additional credentials.
If there are problems with these, sync can fail
(even if auth works).
To reduce the damage, this change allows in-db users to still log in,
even if sync failed.
(As long as they can be authenticated).
> Allow login if LDAP auth works, but sync fails.

- amivapi/tests/users/test_user_cleanup.py
- amivapi/users/cleanup.py
The AMIV API currently has ~13'000 users. To keep the database clean, inactive users, i.e. non-members which didn't log in for the past 12 months, should be deleted from the database.
> User cleanup

- amivapi/auth/sessions.py
- amivapi/events/validation.py
- amivapi/ldap.py
- amivapi/tests/joboffers/test_joboffers.py
- amivapi/tests/test_ldap.py
- amivapi/tests/utils.py
If some LDAP fields are not present in the LDAP response of ETH, the whole user synchronization fails currently and the users cannot log in as described in #436 (Closes #436).
This PR ensures that the users can still successfully log in even if the user synchronization fails but the initial authentication with the LDAP server was successful.
The data processing of the LDAP response is made more failure tolerant. If a field which we expect to exist in the LDAP response is not available, we just skip processing that specific field but still handle the other fields. This makes it a bit harder to spot and debug potential issues with the LDAP sync.
If we want to make that more transparent, we could add further logging messages pointing out which fields were skipped.
> Ldap login without sync

- requirements.txt
Eve-Swagger does not include the `title` field for schema properties although the used OpenAPI specification also defines the `title` field.
This PR updates to the latest version of our fork of eve-swagger which includes the `title` field.
> Update eve-swagger to include title for schema properties

- .github/workflows/ci.yml
Ubuntu-22.04 has no out-of-the-box support for Mongo 5. Therefore we keep using ubuntu-20.04.
> Fix issue with CI pipeline

- .github/workflows/ci.yml
- tox.ini
New version of some dependencies do not support Python 3.7 anymore. As we use a newer Python version anyway, we should drop this support too.
> Drop support for Python 3.7

- amivapi/events/model.py
- amivapi/events/validation.py
- amivapi/tests/events/test_model.py
- amivapi/tests/events/test_validators.py
- amivapi/tests/test_validation.py
- amivapi/validation.py
The requirement emerged to have events organized solely by companies (with their own registration tool) listed on a separate page on the amiv website.
In order to be able to distinguish those different event types, a new field `type` is introduced which adds three different types of events:
| Type | Description |
| --------- | -------------------|
| `internal` | Events organized by amiv. These are the events as we have them so far in our system. |
| `external` | Events organized by companies which are listed on a completely separate page on the amiv website. |
| `announcement` | Special event type for future use to be able to show announcements on the amiv website and other infoscreens without showing them on the events page. |
In addition we also introduce the new field …
> Add fields `external_registration` and `type` to the events resource

- amivapi/events/authorization.py
- amivapi/events/emails.py
- amivapi/events/model.py
- amivapi/tests/events/test_auth.py
- amivapi/tests/events/test_model.py
- amivapi/tests/fixtures.py
- test_performance.py
The requirement emerged to have different signup and signoff deadlines, so that users can still signoff when users cannot signoff themselves anymore.
**Important Note**
The new field is required if a registration window is given. This means that the existing data has to be migrated when deploying this feature.
> Add `time_deregister_end` field to events resource

- .github/dependabot.yml
Update the dependabot configuration so that certain updates are grouped together in a single PR.
> Allow grouping of dependabot PRs

- amivapi/events/__init__.py
- amivapi/events/queue.py
- amivapi/tests/events/test_emails.py
Tackling issue #493 of missing notifications if eventsignups items are updated via PATCH requests. The corresponding hook was missing.
> Issue 493: Fix missing email notifications on manual waitlist updates

- amivapi/auth/sessions.py
- amivapi/ldap.py
- Fixes the LDAP sync issue for users which are not enrolled at ETH anymore.
- Allows for ETH members to authenticate against LDAP by using their ETH email address (Resolves #598)
> Enhance Authentication

- amivapi/templates/events_accept.html
there are people who accidently click the button. there are even former Kulturis who do that.
> clearer signoff text in email.

- .github/workflows/ci.yml
- Dockerfile
- codecov.yml
- docker-compose.yml
- requirements.txt
- tox.ini
update to py3.12 should bring performance and maybe stability.
python 3.8 is EOL, therefore we also remove it. 
decreased agressiveness of codecov as it wouldn't let this PR through even though no actual line of code has changed.
> python 12 dev

- amivapi/events/emails.py
- amivapi/events/queue.py
- amivapi/templates/events_waitingListManual.html
- amivapi/templates/events_waitingListManual.txt
- amivapi/tests/events/test_emails.py
Send a different email if a person is put on the waitinglist for an event with manual acceptance that still has free spots.
This essentially fixes the same problem as #624 but with different emails, which I only noticed after I had already implemented the changes.
> Send a different email for waitinglist on manually accepted events
