- amivapi/authentication.py
- amivapi/bootstrap.py
- amivapi/schemas.py
- amivapi/tests/ldap_integration.py
- amivapi/tests/test_sessions.py
Closes #120 
All eth members can log in now.
Post to /session is now handled by Eve.
> Login with hook

- amivapi/events/model.py
- amivapi/tests/events/test_validators.py
- amivapi/tests/fixtures.py
Added time_advertising_start, time_advertising_end and priority to events.
Also changed one test to create a temporary resource, to make it easier to add fields later.
> Added display time fields to events

- test_performance.py
Just small fixes for the performance script.
> Improved performance test, works without certificate for HTTPS now

- amivapi/tests/fixtures.py
- requirements.txt
Needed to fix some part of fixtures as well since post_internal returns 5 values ins Eves newest version.
> New Eve version (my fork currently, for boolean serialization.

- amivapi/beverages/__init__.py
- amivapi/bootstrap.py
- amivapi/tests/beverages/test_beverages.py
> Renamed purchases to beverages

- amivapi/auth/apikeys.py
- amivapi/auth/sessions.py
- amivapi/groups/model.py
- amivapi/users/model.py
I went through some models and fixed minor format errors and added some more documentation.
I recommend squashing for merging.
> Some format and docs fixes

- amivapi/auth/sessions.py
- amivapi/bootstrap.py
- amivapi/cli.py
- amivapi/ldap.py
- amivapi/tests/ldap_integration.py
- amivapi/tests/test_ldap.py
- requirements.txt
First of all, the structure of ldap.py is now simplified. The class is dropped
and replaced by a few module level functions which are easier to understand.
Next the functions themselves have been rearranged to be easier to test.
Some premature optimization has been removed: The updating of all users
now uses the same function as the one for one user only, since there were not
really noticable performance differences. Again, this simplifies testing.
Speaking of testing: Using mock, all ldap functions are now tested.
There still are some integration tests to verify everything actually works with the
eth ldap.
Finally a few changes in bootstrap, cli and sessions to use the new functions.
After all I am quite happy with this version now. A few points are still up for improvement and I have …
> Ldap improvements

- amivapi/auth/apikeys.py
- amivapi/auth/sessions.py
- amivapi/auth/utils.py
Also they use 256 bit entropy instead of 2048
> Create all tokens with URL safe characters

- amivapi/auth/utils.py
- amivapi/settings.py
> Reduce security

- amivapi/auth/sessions.py
- amivapi/groups/model.py
- amivapi/studydocs/authorization.py
- amivapi/tests/groups/test_model.py
- amivapi/utils.py
> auth hooks can work with embedded relations

- amivapi/groups/model.py
- amivapi/settings.py
- amivapi/studydocs/model.py
- amivapi/users/model.py
Some indices were also added to speed up the regex queries.
> Enable regex queries

- amivapi/cron.py
- amivapi/tests/test_cron.py
> Add Function to update the scheduling of a task

- amivapi/bootstrap.py
- amivapi/utils.py
- amivapi/validation.py
utils.py is getting crowded :^)
> Main validator in separate file

- .travis.yml
- README.md
- amivapi/bootstrap.py
- amivapi/cli.py
- amivapi/settings.py
- amivapi/tests/utils.py
See commit messages for description :)
> Zero config api

- README.md
- docs/Cheatsheet.md
Our docs are bad, so maybe this helps a bit to clear the frequently asked questions.
> Add a cheatsheet

- README.md
- amivapi/settings.py
The docker instructions were not quite working, since the api could not access the db container. Fixed now.
> Improve Docker README, reset settings.

- amivapi/events/model.py
- amivapi/tests/events/test_model.py
> Add cascading delete to eventsignups

- README.md
- amivapi/settings.py
- amivapi/tests/users/test_subscriberlist.py
- amivapi/users/__init__.py
- amivapi/users/subscriberlist.py
> Allow newsletter subscriber export

- amivapi/settings.py
- amivapi/tests/test_media.py
- amivapi/validation.py
Cerberus is too dumb for the current `2 * tuple()` format, so I fixed it^^
> Fix schema validation

- amivapi/settings.py
> Fix typo in settings.py

- amivapi/events/authorization.py
- amivapi/events/model.py
- amivapi/groups/model.py
- amivapi/tests/events/test_auth.py
- amivapi/tests/test_fixtures.py
Some small changes. Closes #371.
> Add moderators

- amivapi/blacklist/__init__.py
- amivapi/blacklist/emails.py
- amivapi/settings.py
- amivapi/tests/blacklist/test_emails.py
Addes some functions that send out an email to a user everytime a new
entry on the blacklist is created for him or one of his entries changed
(patched). The emails include the reason for the blacklist entry and the
price if it exists.
> Adds email send functionality to blacklist

- amivapi/events/__init__.py
- amivapi/events/model.py
- amivapi/events/projections.py
- amivapi/tests/events/test_projections.py
* Add documentation for position field (Fixes #405)
* Add position field in post response (Fixes #410)
> Update position field of eventsignups

- amivapi/documentation/Cheatsheet.md
cheatsheet.md, Category Filtering
`/events?where={"$time_start":{"$gt":"2018-06-06T10:00:00Z"}}` -->` /events?where={"time_start":{"$gt":"2018-06-06T10:00:00Z"}} `
`/events?where={"$or":{"title_en":"Party","title_de":"Feier"}}` -->` /events?where={"$or":[{"title_en":"Party","title_de":"Feier"}]}`
> Fixed category Filtering in cheatsheet.md

- .github/workflows/ci.yml
- Dockerfile
- amivapi/documentation/__init__.py
- amivapi/documentation/update_documentation.py
- amivapi/tests/utils.py
- requirements.txt
- tox.ini
Add support for Python version 3.10 and set it as the default version.
> Add support for Python 3.10

- amivapi/joboffers/__init__.py
- amivapi/tests/joboffers/test_joboffers.py
> made joboffers .jpg compatible

- amivapi/users/usersync.py
> fix usersync return
